import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { ExcelReportService } from './excel-report.service';
import { ReportFilterRequest, ReportResponse, ReportDataRow } from './excel-report.models';

@Component({
  selector: 'app-excel-report',
  templateUrl: './excel-report.component.html',
  styleUrls: ['./excel-report.component.scss'],
  standalone: true,
  imports: [CommonModule]
})
export class ExcelReportComponent {
  @Input() filters: ReportFilterRequest = {
    mode: 'Inward',
    type: 'Size'
  };

  constructor(private excelReportService: ExcelReportService) { }

  public downloadDeliveryChallanExcel(): void {
    // 1. Fetch Dynamic Data from API
    this.excelReportService.getDeliveryChallanReport(this.filters).subscribe({
      next: (response) => {
        // 2. Generate Excel with Dynamic Data
        this.generateExcel(response).then((workbook) => {
          workbook.xlsx.writeBuffer().then((buffer: any) => {
            const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
            saveAs(blob, 'Delivery_Challan_Report.xlsx');
          });
        });
      },
      error: (err) => {
        console.error('Failed to generate Excel report', err);
        alert('Failed to generate report. Ensure backend is running.');
      }
    });
  }

  private async generateExcel(reportData: ReportResponse): Promise<ExcelJS.Workbook> {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Delivery Challan');
    const cellBorder = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

    // Determine the number of total columns.
    // Static columns: S.NO, DC NO, DATE, STYLE NO, DESIGN NAME, COLOUR (6)
    // Dynamic columns: reportData.dynamicColumns.length
    // Total (Bits): 1
    const dynColsCount = reportData.dynamicColumns.length;
    const totalCols = 6 + dynColsCount + 1; // 6 static + dynamic + 1 total

    // Helper to get letter for column (e.g., A=1, B=2, Z=26, AA=27). We only need up to ~AZ.
    const getColLetter = (colNum: number) => {
      let temp, letter = '';
      while (colNum > 0) {
        temp = (colNum - 1) % 26;
        letter = String.fromCharCode(temp + 65) + letter;
        colNum = (colNum - temp - 1) / 26;
      }
      return letter;
    };

    const lastColLetter = getColLetter(totalCols);

    // ---- Header Section ----
    ws.mergeCells(`A1:${lastColLetter}1`);
    ws.getCell('A1').value = 'S.S. EMBROIDERY';
    ws.getCell('A1').font = { name: 'Arial', size: 20, bold: true, color: { argb: 'FF1F497D' } };
    ws.getCell('A1').alignment = { vertical: 'middle', horizontal: 'center' };

    ws.mergeCells(`A2:${lastColLetter}2`);
    ws.getCell('A2').value = 'DELIVERY CHALLAN REPORT (SIZE BASED)';
    ws.getCell('A2').font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FF385D3F' } };
    ws.getCell('A2').alignment = { vertical: 'middle', horizontal: 'center' };

    // Dynamic From Date and To Date
    let fromDateStr = 'N/A';
    let toDateStr = 'N/A';
    if (reportData.data.length > 0) {
      const parsedDates = reportData.data.map(r => {
        if (!r.date) return NaN;
        const parts = r.date.split('-');
        if (parts.length === 3) return new Date(`${parts[2]}-${parts[1]}-${parts[0]}`).getTime();
        return new Date(r.date).getTime();
      }).filter(d => !isNaN(d));

      if (parsedDates.length > 0) {
        const minD = new Date(Math.min(...parsedDates));
        const maxD = new Date(Math.max(...parsedDates));
        const formatD = (d: Date) => `${d.getDate().toString().padStart(2, '0')}-${(d.getMonth() + 1).toString().padStart(2, '0')}-${d.getFullYear()}`;
        fromDateStr = formatD(minD);
        toDateStr = formatD(maxD);
      }
    }

    const now = new Date();
    const generatedOnStr = `${now.getDate().toString().padStart(2, '0')}-${(now.getMonth() + 1).toString().padStart(2, '0')}-${now.getFullYear()} ${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;

    const metadataRightCol = getColLetter(Math.max(2, totalCols - 2));

    ws.getCell('B4').value = `From Date    :   ${fromDateStr}`;
    ws.getCell('B4').font = { bold: true };
    ws.getCell(`${metadataRightCol}4`).value = `Generated On :   ${generatedOnStr}`;
    ws.getCell(`${metadataRightCol}4`).font = { bold: true };

    ws.getCell('B5').value = `To Date        :   ${toDateStr}`;
    ws.getCell('B5').font = { bold: true };
    ws.getCell(`${metadataRightCol}5`).value = 'Generated By :   Admin';
    ws.getCell(`${metadataRightCol}5`).font = { bold: true };

    // Green line across row 6
    ws.mergeCells(`A6:${lastColLetter}6`);
    ws.getCell('A6').border = { bottom: { style: 'medium', color: { argb: 'FF385D3F' } } };

    // ---- Summary Cards ----
    const summaryCardHeaderStyle = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2EFDA' } },
      font: { bold: true, color: { argb: 'FF385D3F' } },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;

    const summaryCardValueStyle = {
      font: { bold: true, size: 16 },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;

    // Distribute 3 cards evenly using basic column maths, starting from B (2) to totalCols-1.
    // Defaulting to 12 columns span if totalCols is too small.
    const availableSpan = Math.max(12, totalCols - 2);
    const cardWidth = Math.floor(availableSpan / 3);

    // Card 1: TOTAL RECORDS
    let startC = 2; let endC = startC + cardWidth - 1;
    ws.mergeCells(`${getColLetter(startC)}8:${getColLetter(endC)}8`);
    ws.getCell(`${getColLetter(startC)}8`).value = 'TOTAL RECORDS';
    ws.getCell(`${getColLetter(startC)}8`).style = summaryCardHeaderStyle;
    ws.mergeCells(`${getColLetter(startC)}9:${getColLetter(endC)}9`);
    ws.getCell(`${getColLetter(startC)}9`).value = reportData.summary.totalRecords;
    ws.getCell(`${getColLetter(startC)}9`).style = summaryCardValueStyle;

    // Card 2: TOTAL BITS COUNT
    startC = endC + 1; endC = startC + cardWidth - 1;
    ws.mergeCells(`${getColLetter(startC)}8:${getColLetter(endC)}8`);
    ws.getCell(`${getColLetter(startC)}8`).value = 'TOTAL BITS COUNT';
    ws.getCell(`${getColLetter(startC)}8`).style = summaryCardHeaderStyle;
    ws.mergeCells(`${getColLetter(startC)}9:${getColLetter(endC)}9`);
    ws.getCell(`${getColLetter(startC)}9`).value = reportData.summary.totalBitsCount;
    ws.getCell(`${getColLetter(startC)}9`).style = summaryCardValueStyle;

    // Card 3: TOTAL METER
    startC = endC + 1; endC = startC + cardWidth - 1;
    ws.mergeCells(`${getColLetter(startC)}8:${getColLetter(endC)}8`);
    ws.getCell(`${getColLetter(startC)}8`).value = 'TOTAL METER';
    ws.getCell(`${getColLetter(startC)}8`).style = summaryCardHeaderStyle;
    ws.mergeCells(`${getColLetter(startC)}9:${getColLetter(endC)}9`);
    ws.getCell(`${getColLetter(startC)}9`).value = reportData.summary.totalMeter;
    ws.getCell(`${getColLetter(startC)}9`).style = summaryCardValueStyle;

    // ---- Main Table ----
    let currentRowIdx = 11;
    ws.mergeCells(`A${currentRowIdx}:${lastColLetter}${currentRowIdx}`);
    ws.getCell(`A${currentRowIdx}`).value = 'DELIVERY CHALLAN (SIZE WISE)';
    ws.getCell(`A${currentRowIdx}`).style = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F497D' } },
      font: { color: { argb: 'FFFFFFFF' }, bold: true, size: 12 },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;
    currentRowIdx++;

    // Table Headers
    const tableHeaderStyleUI = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDAE3F3' } },
      font: { color: { argb: 'FF1F497D' }, bold: true },
      border: cellBorder,
      alignment: { horizontal: 'center', vertical: 'middle' }
    } as any;

    const tableHeaders = ['S.NO', 'DC NO', 'DATE', 'STYLE NO', 'DESIGN NAME', 'COLOUR', ...reportData.dynamicColumns, 'TOTAL (BITS)'];
    ws.insertRow(currentRowIdx, tableHeaders);
    const headerRow = ws.getRow(currentRowIdx);
    for (let c = 1; c <= totalCols; c++) {
      headerRow.getCell(c).style = tableHeaderStyleUI;
    }
    currentRowIdx++;

    // Size-wise totals tracking
    const sizeTotals: { [key: string]: number } = {};
    reportData.dynamicColumns.forEach(c => sizeTotals[c] = 0);

    // Table Body
    reportData.data.forEach(r => {
      const dataRow = [
        r.sno, r.dcNo, r.date, r.styleNo, r.designName, r.colour
      ];

      reportData.dynamicColumns.forEach(col => {
        const val = r.dynamicValues[col] || '-';
        dataRow.push(val as never);
        if (typeof val === 'number') sizeTotals[col] += val;
      });
      dataRow.push(r.totalBits as never);

      ws.insertRow(currentRowIdx, dataRow);
      const row = ws.getRow(currentRowIdx);
      for (let c = 1; c <= totalCols; c++) {
        row.getCell(c).border = cellBorder as any;
        row.getCell(c).alignment = { vertical: 'middle', horizontal: 'center' };
      }
      currentRowIdx++;
    });

    // Size Wise Total Row
    ws.mergeCells(`A${currentRowIdx}:F${currentRowIdx}`);
    ws.getCell(`A${currentRowIdx}`).value = 'SIZE WISE TOTAL (BITS)';

    let cIdx = 7; // Col G
    reportData.dynamicColumns.forEach(col => {
      ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = sizeTotals[col];
      cIdx++;
    });
    ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = reportData.summary.totalBitsCount;

    const totalRowStyle = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } },
      font: { bold: true },
      border: cellBorder,
      alignment: { horizontal: 'center', vertical: 'middle' }
    } as any;

    for (let c = 1; c <= totalCols; c++) {
      ws.getCell(currentRowIdx, c).style = totalRowStyle;
    }

    // ---- Grand Total Section ----
    currentRowIdx += 3; // Gap
    ws.mergeCells(`B${currentRowIdx}:${lastColLetter}${currentRowIdx}`);
    ws.getCell(`B${currentRowIdx}`).value = 'SIZE WISE GRAND TOTAL (BITS)';
    ws.getCell(`B${currentRowIdx}`).style = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF385D3F' } },
      font: { color: { argb: 'FFFFFFFF' }, bold: true },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;
    currentRowIdx++;

    ws.mergeCells(`B${currentRowIdx}:F${currentRowIdx}`);
    ws.getCell(`B${currentRowIdx}`).value = 'SIZE';
    const grandTotalHeaderStyle = {
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2EFDA' } },
      font: { bold: true },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;

    for (let c = 2; c <= 6; c++) ws.getCell(currentRowIdx, c).style = grandTotalHeaderStyle;

    cIdx = 7;
    reportData.dynamicColumns.forEach(sz => {
      ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = sz;
      ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).style = grandTotalHeaderStyle;
      cIdx++;
    });
    ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = 'GRAND TOTAL';
    ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).style = grandTotalHeaderStyle;
    currentRowIdx++;

    ws.mergeCells(`B${currentRowIdx}:F${currentRowIdx}`);
    ws.getCell(`B${currentRowIdx}`).value = 'TOTAL (BITS)';
    const grandTotalValueStyle = {
      font: { bold: true },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: cellBorder
    } as any;
    for (let c = 2; c <= 6; c++) ws.getCell(currentRowIdx, c).style = grandTotalValueStyle;

    cIdx = 7;
    reportData.dynamicColumns.forEach(sz => {
      ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = sizeTotals[sz];
      ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).style = grandTotalValueStyle;
      cIdx++;
    });
    ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).value = reportData.summary.totalBitsCount;
    ws.getCell(`${getColLetter(cIdx)}${currentRowIdx}`).style = grandTotalValueStyle;

    currentRowIdx += 2;
    ws.mergeCells(`A${currentRowIdx}:F${currentRowIdx}`);
    ws.getCell(`A${currentRowIdx}`).value = 'Note : "-" Represents zero / not applicable.';
    ws.getCell(`A${currentRowIdx}`).font = { bold: true, color: { argb: 'FF1F497D' }, size: 10 };

    // Auto‑width based on column name and content
    ws.getColumn('A').width = 8;  // S.NO
    ws.getColumn('B').width = 15; // DC NO
    ws.getColumn('C').width = 15; // DATE
    ws.getColumn('D').width = 25; // STYLE NO
    ws.getColumn('E').width = 35; // DESIGN NAME
    ws.getColumn('F').width = 20; // COLOUR

    for (let c = 7; c <= totalCols - 1; c++) {
      ws.getColumn(c).width = 10;
    }
    ws.getColumn(totalCols).width = 18; // TOTAL (BITS)

    return wb;
  }
}

