import { Injectable } from '@angular/core';
import * as ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { StockManagementReport } from './excel-report.models';

@Injectable({
  providedIn: 'root'
})
export class StockManagementExcelService {

  public async generateAndDownload(reportData: StockManagementReport): Promise<void> {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Stock Management', {
      pageSetup: {
        paperSize: 9, // A4
        orientation: 'landscape',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        margins: { left: 0.2, right: 0.2, top: 0.3, bottom: 0.3, header: 0.1, footer: 0.1 }
      },
      headerFooter: { oddFooter: '&LReport Generated On: &D &T&CThis is a system generated report.&RPage &P of &N' }
    });

    // Theme Colors
    const primaryBlue = 'FF0B3B8C';
    const accentGreen = 'FF0E7C3A';
    const lightBorder = 'FF8EA9DB'; // Darker blue for visibility

    // Helper for merged cell borders
    const applyMergedBorder = (sRow: number, eRow: number, sCol: number, eCol: number, borderDef: any) => {
      for (let r = sRow; r <= eRow; r++) {
        for (let c = sCol; c <= eCol; c++) {
          ws.getCell(r, c).border = {
            top: r === sRow ? borderDef.top : undefined,
            bottom: r === eRow ? borderDef.bottom : undefined,
            left: c === sCol ? borderDef.left : undefined,
            right: c === eCol ? borderDef.right : undefined
          } as any;
        }
      }
    };
    const white = 'FFFFFFFF';
    const darkGray = 'FF333333';
    const rowAltBlue = 'FFF4F7FC';

    // Fonts
    const fontTitle = { name: 'Calibri', size: 24, bold: true, color: { argb: primaryBlue } };
    const fontSubtitle = { name: 'Calibri', size: 18, bold: true, color: { argb: accentGreen } };
    const fontNormal = { name: 'Calibri', size: 11, color: { argb: darkGray } };
    const fontBold = { name: 'Calibri', size: 11, bold: true, color: { argb: darkGray } };
    const fontHeader = { name: 'Calibri', size: 11, bold: true, color: { argb: white } };
    
    const cellBorderThin = { top: { style: 'thin', color: { argb: lightBorder } }, left: { style: 'thin', color: { argb: lightBorder } }, bottom: { style: 'thin', color: { argb: lightBorder } }, right: { style: 'thin', color: { argb: lightBorder } } } as any;

    const totalCols = 11;
    const colWidths = [
      8,  // A: S.NO
      15, // B: DATE
      12, // C: TYPE
      18, // D: DC NO
      30, // E: COMPANY
      15, // F: STYLE NO
      25, // G: DESIGN NAME
      15, // H: COLOUR
      14, // I: INWARD QTY
      15, // J: OUTWARD QTY
      15  // K: AVAILABLE QTY
    ];
    
    for (let c = 1; c <= totalCols; c++) {
        ws.getColumn(c).width = colWidths[c - 1];
    }

    // ---- HEADER ----
    let logoId: number | undefined;
    try {
      const res = await fetch('/logo.jpg');
      if (res.ok) {
        const buffer = await res.arrayBuffer();
        logoId = wb.addImage({
          buffer: buffer,
          extension: 'jpeg',
        });
      }
    } catch (e) {
      console.warn('Could not fetch logo.jpg for Excel generation', e);
    }

    ws.mergeCells('A1:B3');
    if (logoId !== undefined) {
      ws.addImage(logoId, 'A1:B3');
    } else {
      const logoCell = ws.getCell('A1');
      logoCell.value = 'S.S.E\nLOGO';
      logoCell.font = { name: 'Calibri', size: 16, bold: true, color: { argb: primaryBlue } };
      logoCell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    }
    applyMergedBorder(1, 3, 1, 2, cellBorderThin);

    ws.mergeCells('C1:I2');
    ws.getCell('C1').value = 'S.S. EMBROIDERY';
    ws.getCell('C1').font = fontTitle;
    ws.getCell('C1').alignment = { horizontal: 'center', vertical: 'middle' };

    ws.mergeCells('C3:I3');
    ws.getCell('C3').value = 'STOCK MANAGEMENT REPORT';
    ws.getCell('C3').font = fontSubtitle;
    ws.getCell('C3').alignment = { horizontal: 'center', vertical: 'middle' };

    const now = new Date();
    const dateStr = `${now.getDate().toString().padStart(2, '0')}-${(now.getMonth() + 1).toString().padStart(2, '0')}-${now.getFullYear()}`;
    const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    ws.mergeCells('J1:K1'); ws.getCell('J1').value = `Generated On :   ${dateStr}`; ws.getCell('J1').font = fontNormal; ws.getCell('J1').alignment = { horizontal: 'right', vertical: 'middle' };
    ws.mergeCells('J2:K2'); ws.getCell('J2').value = `Generated Time :   ${timeStr}`; ws.getCell('J2').font = fontNormal; ws.getCell('J2').alignment = { horizontal: 'right', vertical: 'middle' };
    ws.mergeCells('J3:K3'); ws.getCell('J3').value = `Generated By :   Admin`; ws.getCell('J3').font = fontNormal; ws.getCell('J3').alignment = { horizontal: 'right', vertical: 'middle' };

    // ---- FILTER SECTION ----
    for(let r = 5; r <= 6; r++) {
       for(let c = 1; c <= totalCols; c++) {
          ws.getCell(r, c).border = { 
            top: r === 5 ? { style: 'thin', color: { argb: lightBorder } } : undefined,
            bottom: r === 6 ? { style: 'thin', color: { argb: lightBorder } } : undefined,
            left: c === 1 ? { style: 'thin', color: { argb: lightBorder } } : undefined,
            right: c === 11 ? { style: 'thin', color: { argb: lightBorder } } : undefined
          } as any;
       }
    }
    ws.mergeCells('A5:E5'); ws.getCell('A5').value = `  Company :  ${reportData.companyName || 'All'}`; ws.getCell('A5').font = fontBold; ws.getCell('A5').alignment = { vertical: 'middle' };
    ws.mergeCells('A6:E6'); ws.getCell('A6').value = `  Branch   :  ${reportData.branch || 'All Branches'}`; ws.getCell('A6').font = fontBold; ws.getCell('A6').alignment = { vertical: 'middle' };
    ws.mergeCells('F5:K5'); ws.getCell('F5').value = `  From Date :  ${reportData.fromDate || 'N/A'}`; ws.getCell('F5').font = fontBold; ws.getCell('F5').alignment = { vertical: 'middle' };
    ws.mergeCells('F6:K6'); ws.getCell('F6').value = `  To Date     :  ${reportData.toDate || 'N/A'}`; ws.getCell('F6').font = fontBold; ws.getCell('F6').alignment = { vertical: 'middle' };

    // ---- SUMMARY CARDS ----
    const cardSpans = [
      { s: 'A', e: 'B' }, { s: 'C', e: 'D' }, { s: 'E', e: 'E' },
      { s: 'F', e: 'G' }, { s: 'H', e: 'I' }, { s: 'J', e: 'K' }
    ];

    const cards = [
      { title: 'TOTAL ITEMS', value: reportData.summary?.totalRecords || 0 },
      { title: 'TOTAL INWARD', value: reportData.summary?.totalInwardQty || 0 },
      { title: 'TOTAL OUTWARD', value: reportData.summary?.totalOutwardQty || 0 },
      { title: 'AVAILABLE STOCK', value: reportData.summary?.availableStock || 0 },
      { title: 'LOW STOCK', value: reportData.summary?.lowStockItems || 0 },
      { title: 'OUT OF STOCK', value: reportData.summary?.outOfStockItems || 0 }
    ];

    for (let i = 0; i < 6; i++) {
      const span = cardSpans[i];
      ws.mergeCells(`${span.s}8:${span.e}11`);
      const cardCell = ws.getCell(`${span.s}8`);
      cardCell.value = {
        richText: [
          { text: `${cards[i].title}\n\n`, font: { name: 'Calibri', size: 9, color: { argb: 'FF555555' } } },
          { text: `${Number(cards[i].value).toLocaleString()}`, font: { name: 'Calibri', size: 20, bold: true, color: { argb: 'FF000000' } } }
        ]
      };
      cardCell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
      
      const sColIdx = ws.getColumn(span.s).number;
      const eColIdx = ws.getColumn(span.e).number;
      applyMergedBorder(8, 11, sColIdx, eColIdx, cellBorderThin);
    }

    // ---- SUMMARY BAR ----
    const barSpans = [
      { s: 'A', e: 'D', title: 'TOTAL INWARD QTY', value: reportData.summary?.totalInwardQty || 0, vColor: accentGreen },
      { s: 'E', e: 'G', title: 'TOTAL OUTWARD QTY', value: reportData.summary?.totalOutwardQty || 0, vColor: primaryBlue },
      { s: 'H', e: 'K', title: 'AVAILABLE STOCK', value: reportData.summary?.availableStock || 0, vColor: accentGreen }
    ];

    for (let i = 0; i < 3; i++) {
      const span = barSpans[i];
      ws.mergeCells(`${span.s}13:${span.e}15`);
      const barCell = ws.getCell(`${span.s}13`);
      barCell.value = {
        richText: [
          { text: `${span.title}\n`, font: { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF555555' } } },
          { text: `${Number(span.value).toLocaleString()}`, font: { name: 'Calibri', size: 18, bold: true, color: { argb: span.vColor } } }
        ]
      };
      barCell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
      
      const sColIdx = ws.getColumn(span.s).number;
      const eColIdx = ws.getColumn(span.e).number;
      applyMergedBorder(13, 15, sColIdx, eColIdx, cellBorderThin);
    }

    // ---- LATEST TRANSACTIONS HEADER ----
    let rowIdx = 17;
    ws.mergeCells(`A${rowIdx}:K${rowIdx}`);
    ws.getCell(`A${rowIdx}`).value = 'LATEST TRANSACTIONS';
    ws.getCell(`A${rowIdx}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: primaryBlue } };
    ws.getCell(`A${rowIdx}`).font = { name: 'Calibri', size: 12, bold: true, color: { argb: white } };
    ws.getCell(`A${rowIdx}`).alignment = { horizontal: 'center', vertical: 'middle' };
    
    rowIdx++;
    const transHeaders = ['S.NO', 'DATE', 'TYPE', 'DC NO', 'COMPANY', 'STYLE NO', 'DESIGN NAME', 'COLOUR', 'INWARD QTY', 'OUTWARD QTY', 'AVAILABLE QTY'];
    ws.insertRow(rowIdx, transHeaders);
    
    for (let c = 1; c <= totalCols; c++) {
      const hc = ws.getCell(rowIdx, c);
      hc.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: primaryBlue } };
      hc.font = fontHeader;
      hc.alignment = { horizontal: 'center', vertical: 'middle' };
      hc.border = cellBorderThin;
    }
    
    ws.autoFilter = `A${rowIdx}:K${rowIdx}`;
    rowIdx++;

    // ---- DATA ROWS ----
    let sno = 1;
    let sumInward = 0, sumOutward = 0;
    
    if (reportData.transactions && reportData.transactions.length > 0) {
      reportData.transactions.forEach(t => {
        const d = new Date(t.date || t.createdDate);
        const dateStr = !isNaN(d.getTime()) ? `${d.getDate().toString().padStart(2, '0')}-${(d.getMonth() + 1).toString().padStart(2, '0')}-${d.getFullYear()}` : '';
        
        const inQty = t.inwardQty || 0;
        const outQty = t.outwardQty || 0;
        
        sumInward += inQty;
        sumOutward += outQty;

        const rowData = [sno++, dateStr, t.type, t.dcNo || '-', t.companyName || '-', t.styleNo || '-', t.designName || '-', t.color || '-', inQty, outQty, '-'];
        ws.insertRow(rowIdx, rowData);
        
        for (let c = 1; c <= totalCols; c++) {
          const cell = ws.getCell(rowIdx, c);
          cell.border = cellBorderThin;
          
          if (rowIdx % 2 === 0) {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowAltBlue } };
          }
          
          cell.font = fontNormal;
          
          // Alignments
          if (c === 2) cell.alignment = { horizontal: 'center', vertical: 'middle' };
          else if (c > 8) cell.alignment = { horizontal: 'right', vertical: 'middle' };
          else cell.alignment = { horizontal: 'left', vertical: 'middle' };
          
          // Badge Styling
          if (c === 3) {
             cell.alignment = { horizontal: 'center', vertical: 'middle' };
             if (t.type === 'INWARD') {
                cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2EFDA' } };
                cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: accentGreen } };
             } else if (t.type === 'OUTWARD') {
                cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFCE4D6' } };
                cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FFC00000' } };
             }
          }
          
          if (c === 9 && inQty > 0) {
             cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: accentGreen } };
          }
          if (c === 10 && outQty > 0) {
             cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFC00000' } };
          }
          if (c === 11) {
             cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: accentGreen } };
          }
        }
        rowIdx++;
      });
    } else {
        ws.mergeCells(`A${rowIdx}:K${rowIdx}`);
        ws.getCell(`A${rowIdx}`).value = 'No Records Found';
        ws.getCell(`A${rowIdx}`).font = fontBold;
        ws.getCell(`A${rowIdx}`).alignment = { horizontal: 'center', vertical: 'middle' };
        ws.getCell(`A${rowIdx}`).border = cellBorderThin;
        rowIdx++;
    }

    // ---- TOTALS SECTION ----
    ws.mergeCells(`A${rowIdx}:H${rowIdx}`);
    ws.getCell(`A${rowIdx}`).value = 'TOTALS';
    
    const totalFill = { type: 'pattern', pattern: 'solid', fgColor: { argb: primaryBlue } } as any;
    
    for(let c = 1; c <= 11; c++) {
       const tc = ws.getCell(rowIdx, c);
       tc.fill = totalFill;
       tc.border = cellBorderThin;
       if (c <= 8) {
         tc.font = { name: 'Calibri', size: 12, bold: true, color: { argb: white } };
         tc.alignment = { horizontal: 'center', vertical: 'middle' };
       } else {
         tc.font = { name: 'Calibri', size: 12, bold: true, color: { argb: white } };
         tc.alignment = { horizontal: 'right', vertical: 'middle' };
       }
    }
    
    ws.getCell(rowIdx, 9).value = sumInward;
    ws.getCell(rowIdx, 10).value = sumOutward;
    ws.getCell(rowIdx, 11).value = '-';
    
    await this.finalizeAndDownload(wb, 'Stock_Management_Report');
  }

  private async finalizeAndDownload(wb: ExcelJS.Workbook, baseName: string) {
    const buffer = await wb.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    
    const now = new Date();
    const ts = `${now.getFullYear()}${(now.getMonth()+1).toString().padStart(2,'0')}${now.getDate().toString().padStart(2,'0')}_${now.getHours().toString().padStart(2,'0')}${now.getMinutes().toString().padStart(2,'0')}${now.getSeconds().toString().padStart(2,'0')}`;
    saveAs(blob, `${baseName}_${ts}.xlsx`);
  }
}
